

name: EC2 Deployment
on: 
  push:
    branches: 
      - deploy
  pull_request:
    branches: 
      - deploy
  types: [closed]
jobs:
  deployment:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checks out this branch
        uses: actions/checkout@v3
      - name: whoisthis
        run: |
          ifconfig
          echo ${GITHUB_SHA}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build dist and deposit into server
        run: |
          ls
          rm -rf node_modules
          npm i -legacy-peer-deps
          npm run client-build-prod
          ls dist
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.SSH_KEY }}
          username: ubuntu
          source: "./dist"
          target: "./"

      # - name: copy file into runner's home
      #   run: cp ./dev-hooks/deployment-hooks/deployec2gomoonbe.sh ./deployec2gomoonbe.sh
      # - name: copy file via ssh key
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_IP }}
      #     key: ${{ secrets.SSH_KEY }}
      #     username: ubuntu
      #     source: "./deployec2gomoonbe.sh"
      #     target: "./"
      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@master
      #   env:
      #     SHA: ${{ github.sha }}
      #   with:
      #     host: ${{ secrets.EC2_IP }}
      #     username: ubuntu
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     envs: SHA
      #     script: |
      #       echo "$SHA"
      #       ./deployec2gomoonbe.sh "$SHA"
